### ISSUE TITLE
Broken pipe error occurs occasionally

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#12]
Device: Android 8.1
Latest version of NetBare Sample

I visited the following page: https://www.travelden.co.uk/20-forbidden-places-you-can-never-visit?utm_source=taboola&utm_medium=referral&utm_term=tmg-birminghammail&utm_content=157819389&utm_site=tmg-birminghammail&utm_campaign_item=157819389&utm_campaign=ForbiddenDestinations-GlobalC and an error was reported in logcat:

2019-02-18 13:39:36.083 11516-11581/com.github.megatronking.netbare.sample E/NetBare: Broken pipe
    java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:53)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:510)
        at com.github.megatronking.netbare.tunnel.TcpTunnel.channelWrite(TcpTunnel.java:77)
        at com.github.megatronking.netbare.tunnel.NioTunnel.onWrite(NioTunnel.java:114)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:141)
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:108)
        at java.lang.Thread.run(Thread.java:764)
2019-02-18 13:39:36.108 11516-11581/com.github.megatronking.netbare.sample E/NetBare: Broken pipe
    java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:53)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:510)
        at com.github.megatronking.netbare.tunnel.TcpTunnel.channelWrite(TcpTunnel.java:77)
        at com.github.megatronking.netbare.tunnel.NioTunnel.onWrite(NioTunnel.java:114)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:141)
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:108)
        at java.lang.Thread.run(Thread.java:764)

Was not able to reproduce this error by re-loading the page, so it may be a random error that is difficult to reproduce.

The page still loaded fine in Chrome, there were no visible signs of a problem.

**Comment by MegatronKing** [comment]
It is difficult for me to find the cause, maybe this is not an issue with NetBare.
