### ISSUE TITLE
MeiZuPro7 Root手机SSL握手失败，证书已信任

### ISSUE THREAD

**Issue by qkmaosjtu** [MegatronKing/NetBare#40]
`2019-10-20 20:56:24.570 30291-30724/com.github.megatronking.netbare.sample E/NetBare: Handshake failed: Invalid handshake status: NOT_HANDSHAKING
    java.io.IOException: Handshake failed: Invalid handshake status: NOT_HANDSHAKING
        at com.github.megatronking.netbare.ssl.SSLCodec.handshake(SSLCodec.java:219)
        at com.github.megatronking.netbare.ssl.SSLCodec.startDecode(SSLCodec.java:192)
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:172)
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:143)
        at com.github.megatronking.netbare.http.HttpSSLResponseCodec.decode(HttpSSLResponseCodec.java:71)
        at com.github.megatronking.netbare.http.HttpSSLCodecInterceptor.decodeResponse(HttpSSLCodecInterceptor.java:233)
        at com.github.megatronking.netbare.http.HttpSSLCodecInterceptor.intercept(HttpSSLCodecInterceptor.java:154)
        at com.github.megatronking.netbare.http.HttpSSLCodecInterceptor.intercept(HttpSSLCodecInterceptor.java:41)
        at com.github.megatronking.netbare.gateway.IndexedInterceptor.intercept(IndexedInterceptor.java:73)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32)
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:104)
        at com.github.megatronking.netbare.http.HttpSniffInterceptor.intercept(HttpSniffInterceptor.java:71)
        at com.github.megatronking.netbare.http.HttpSniffInterceptor.intercept(HttpSniffInterceptor.java:34)
        at com.github.megatronking.netbare.gateway.IndexedInterceptor.intercept(IndexedInterceptor.java:73)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32)
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:104)
        at com.github.megatronking.netbare.http.HttpVirtualGateway.onSpecResponse(HttpVirtualGateway.java:126)
        at com.github.megatronking.netbare.gateway.SpecVirtualGateway.onResponse(SpecVirtualGateway.java:85)
        at com.github.megatronking.netbare.NetBareVirtualGateway.onResponse(NetBareVirtualGateway.java:102)
        at com.github.megatronking.netbare.tunnel.TcpVATunnel$2.onRead(TcpVATunnel.java:134)
        at com.github.megatronking.netbare.tunnel.NioTunnel.onRead(NioTunnel.java:101)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:139)
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:108)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by MegatronKing** [comment]
能提供下host或者ip吗

**Comment by qkmaosjtu** [comment]
> 能提供下host或者ip吗

大佬响应这么迅速！没有特定的host或者ip，比如www.baidu.com也无法访问

**Comment by qkmaosjtu** [comment]
> 能提供下host或者ip吗

提示该网站的安全证书有问题

**Comment by MegatronKing** [comment]
Android 10系统吗？用浏览器打开的？

**Comment by qkmaosjtu** [comment]
> Android 10系统吗？用浏览器打开的？


![image](https://user-images.githubusercontent.com/16631352/67160419-0ca64780-f383-11e9-976e-f778f69316a5.png)

**Comment by qkmaosjtu** [comment]
> Android 10系统吗？用浏览器打开的？

ROOT设备证书需要特别的配置吗？SSL握手失败失败是不是一般是证书问题

**Comment by MegatronKing** [comment]
这个看上去像是代码bug，和证书无关，但是我不是很确定。NetBare开源的代码比较老了，HttpCanary使用的是NetBare的一个闭源分支，你试试HttpCanary能不能正常抓https://www.baidu.com这个

**Comment by qkmaosjtu** [comment]
> HttpCanary

两台这个型号的设备都出现了同样的问题，其他设备没有出现

**Comment by MegatronKing** [comment]
出问题的两台设备型号都是截图这个系统？

**Comment by qkmaosjtu** [comment]
> 出问题的两台设备型号都是截图这个系统？

对的，刚用HttpCanary试了下，抓包是没有问题的

**Comment by qkmaosjtu** [comment]
问个比较小白的问题，/**
         * The <code>SSLEngine</code> is not currently handshaking.
         */
        NOT_HANDSHAKING,
通常会在什么情况下发生？

**Comment by hhhaiai** [comment]
> 这个看上去像是代码bug，和证书无关，但是我不是很确定。NetBare开源的代码比较老了，HttpCanary使用的是NetBare的一个闭源分支，你试试HttpCanary能不能正常抓[https://www.baidu.com这个](https://www.baidu.com%E8%BF%99%E4%B8%AA)
 是否考虑后续还继续开源一波

**Comment by qkmaosjtu** [comment]
> 出问题的两台设备型号都是截图这个系统？
有更新吗？在我把证书导入成系统证书之后仍然有这个问题，看起来不是证书的问题了
![image](https://user-images.githubusercontent.com/16631352/67558070-db45c700-f748-11e9-9ca1-ef34b43327fe.png)

**Comment by fr0zenrain** [comment]
same issue,should be a code bug, will fix?
