### ISSUE TITLE
Crash when visiting cnn.com

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#7]
Tested and reproducible on Android 7, 8.1 and 9 devices

On visiting cnn.com, the page is redirected to https://edition.cnn.com

If this page is opened in Chrome, it is not loaded correctly (screen remains blank) and the following crash occurs:

2019-01-31 13:23:32.418 3029-5047/com.github.megatronking.netbare.sample E/NetBare: Connection reset by peer
    java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:55)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:512)
        at com.github.megatronking.netbare.tunnel.TcpTunnel.channelWrite(TcpTunnel.java:77)
        at com.github.megatronking.netbare.tunnel.NioTunnel.onWrite(NioTunnel.java:114)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:141)
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:108)
        at java.lang.Thread.run(Thread.java:764)

**Comment by wilos** [comment]
I noticed that this error is not happening with the latest version of httpcanary. It is only happening with netbare-sample. So there must be a difference between netbare-sample and httpcanary which is causing the issue. Would it be possible to update netbare-sample to avoid this issue (and some others)? I can see that, in general, httpcanary is more stable/reliable than netbare-sample

**Comment by MegatronKing** [comment]
HttpCanary has the same issue too. You might use a historic version which has the ALPN bug, the bug will cause the browser to use HTTP1.1 instead of HTTP2. I fixed this issue and lead the browser to use HTTP2 correctly. However, there are some bugs when using HTTP2. I am digging.

**Comment by MegatronKing** [comment]
This issue has been fixed.

**Comment by wilos** [comment]
Thanks very much, I can confirm that this is now working fine, great!
