### ISSUE TITLE
为啥解析不了优酷视频的HTTP、HTTPS包啊？

### ISSUE THREAD

**Issue by 411370845** [MegatronKing/NetBare#72]
大佬们，我发现在优酷视频里的有些请求，能解析，有些解析失败，谁能帮我看一下啊？

**Comment by 411370845** [comment]
报了这样的证书错误，作者大大有空的话，能帮忙看看不？
com.youku.phone W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.c.a(SourceFile:300)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.c.a(SourceFile:269)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.c.a(SourceFile:161)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.f.a(SourceFile:256)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.f.a(SourceFile:135)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.f.a(SourceFile:114)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.connection.a.intercept(SourceFile:42)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:147)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:121)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.a.a.intercept(SourceFile:93)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:147)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:121)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.a.intercept(SourceFile:93)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:147)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.j.intercept(SourceFile:168)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:147)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:121)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.huc.OkHttpURLConnection$UnexpectedException$1.intercept(SourceFile:588)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:147)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.b.g.a(SourceFile:121)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.y.g(SourceFile:200)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.y.b(SourceFile:77)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.huc.OkHttpURLConnection.a(SourceFile:460)
2020-08-26 15:26:00.765 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(SourceFile:497)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.huc.b.getResponseCode(SourceFile:111)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at okhttp3.internal.huc.c.getResponseCode(SourceFile:25)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at okhttp3.net.b.b.getResponseCode(SourceFile:180)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at cn.com.mma.mobile.tracking.b.c.a(SourceFile:58)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at cn.com.mma.mobile.tracking.api.d.a(SourceFile:73)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err:     at cn.com.mma.mobile.tracking.api.d.run(SourceFile:48)
2020-08-26 15:26:00.766 24087-25887/com.youku.phone W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err: 	... 30 more
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-08-26 15:26:00.767 24087-25887/com.youku.phone W/System.err: 	... 42 more

**Comment by qkmaosjtu** [comment]
证书问题
